# basic visualization of network run on one event


df:
  parse:
    args:
      sep: '\s+'
      encoding: 'utf-8'
      nrows:
      filepath_or_buffer: 'data_cgem/200.txt'
      names: ['event',  'x', 'y', 'z', 'station', 'track']

  take:
    event_ids: ['1..6000'] # ['1..10'] (list of events with these indexes) or [':'] (all events from df)

    drop_broken_tracks: False # __UNUSED__ drop tracks with the gaps or which does not start at station #0
    convert_to_polar: True
    normalize:
      drop_old: True
    stations_sizes:
      cgem:
        x_minmax: [-166.6, 166.6]
        y_minmax: [-166.6, 166.6]
        z_minmax: [-423.5, 423.5]

visualize:
  draw_scatters_for_tracks: True
  mode: '2d' # '2d'

prepare:
  output_dir: 'output/cgem_6k'
  restrictions:
  mode: 'cgem'
  dphi_minmax: [-0.18, 0.18]
  dz_minmax: [-0.15, 0.15]

with_stdout: False
#  ellipses: True
#
#network: #False
#  network_path: "results/no_vtx_tracknetV2_seed{13}_batch{32}_epoch{27}_loss{1.7983}_acc{0.8842}_circle{3.3569}.h5"




#with_vertex: False

