trainer:
    real_weight: 4   # 0.5 / 0.1
    fake_weight: 0.555 # 0.5 / 0.9

train:
  input_dir: 'output/cgem_6k'
  result_dir: 'cgem_result_6k'
  n_train: 5000
  n_valid: 700
  batch_size: 1
  n_epochs: 384
  preprocess_dataset:

model:
  name: 'gnn_segment_classifier'
  input_dim: 3
  hidden_dim: 128
  n_iters: 2
  loss_func: 'binary_cross_entropy'
  optimizer: 'Adam'
  learning_rate: 0.001