# basic visualization of network run on one event
df:
  parse:
    args:
      sep: '\s+'
      encoding: 'utf-8'
      nrows:
      filepath_or_buffer: 'data_cgem/200.txt'
      names: ['event',  'x', 'y', 'z', 'station', 'track']

  take:
    event_ids: ['12000..13000'] # ['1..10'] (list of events with these indexes) or [':'] (all events from df)

    drop_broken_tracks: False # __UNUSED__ drop tracks with the gaps or which does not start at station #0
    convert_to_polar: True
    normalize:
      drop_old: True
    stations_sizes:
      cgem:
        x_minmax: [-166.6, 166.6]
        y_minmax: [-166.6, 166.6]
        z_minmax: [-423.5, 423.5]

visualize:
  draw_scatters_for_tracks: True
  mode: '2d' # '2d'

prepare:
  output_dir: 'output/cgem_1k_LINEGRAPH_for_test'
  mode: 'cgem'
  linegraph:
    axes: ['r', 'phi', 'z']
    suffix: ['_p', '_c']
    restrictions: [
        [-0.18, 0.18],
        [-0.15, 0.15]
      ]
    weight_r: 0.073
with_stdout: False

evaluate:


