trainer:
    real_weight: 10   # 0.5 / 0.1
    fake_weight: 2 # 0.5 / 0.9

train:
  input_dir: '../for_test'
  result_dir: '../result_colab_8k'
  n_train: 16384
  n_valid: 1024
  batch_size: 20
  n_epochs: 55
  preprocess_dataset:
    filename: 'prepare_stats.csv'
    edge_count_max: 1000
    edge_count_min: 100
    node_count_max: 3000

model:
  name: 'gnn_segment_classifier'
  input_dim: 3
  hidden_dim: 96
  n_iters: 1
  loss_func: 'binary_cross_entropy'
  optimizer: 'Adam'
  learning_rate: 0.001