# basic visualization of network run on one event


df:
  df_path: 'data/train/CC4GeVmb_100_n50k.tsv'
  event_ids: ['1..500'] # ['1..10'] (list of events with these indexes) or [':'] (all events from df)
  read_only_first_lines: 150000
  drop_broken_tracks: True # drop tracks with the gaps or which does not start at station #0
  convert_to_polar: False
  normalize: True
  stations_sizes: [
    [[-1.5, -4.5, 66, 41]],
    [[-1.5, -4.5, 66, 41]],
    [[-1.5, -4.5, 66, 41]],
      # module 0, module 1 FIXED RECTS ON STATION 5 and 6
    [[27.7, -4.5, 66, 41], [-34.7, -4.3, 66, 41]],
    [[40.8, -6.9, 81.6, 45], [-40.8, -6.9, 81.6, 45]],
    [[40.8, -6.9, 81.6, 45], [-40.8, -6.9, 81.6, 45]]
  ]
  z_stations: [32.85, 65.25, 96.65, 129.35, 161.25, 193.85]

visualize:
  draw_scatters_for_tracks: True
  mode: '2d' # '3d'

prepare:
  output_dir: 'output_first'
  restrictions:
    x_min_max: [-0.15, 0.25]
    y_min_max: [-0.3, 0.22]
    weight_max: 0.09

#  ellipses: True
#
#network: #False
#  network_path: "results/no_vtx_tracknetV2_seed{13}_batch{32}_epoch{27}_loss{1.7983}_acc{0.8842}_circle{3.3569}.h5"




#with_vertex: False

