trainer:
    real_weight: 2.0   # 0.5 / 0.1
    fake_weight: 0.555 # 0.5 / 0.9

train:
  input_dir: 'output_20k'
  result_dir: 'result_3.5k'
  n_train: 3200
  n_valid: 400
  batch_size: 1
  n_epochs: 96

model:
  name: 'gnn_segment_classifier'
  input_dim: 3
  hidden_dim: 96
  n_iters: 3
  loss_func: 'binary_cross_entropy'
  optimizer: 'Adam'
  learning_rate: 0.001