trainer:
    real_weight: 5.0   # 0.5 / 0.1
    fake_weight: 0.5 # 0.5 / 0.9

train:
  input_dir: 'output_8k'
  result_dir: 'result_8k'
  n_train: 7200
  n_valid: 800
  batch_size: 5
  n_epochs: 128

model:
  name: 'gnn_segment_classifier'
  input_dim: 3
  hidden_dim: 96
  n_iters: 6
  loss_func: 'binary_cross_entropy'
  optimizer: 'Adam'
  learning_rate: 0.001